export const RECEIVE_REQUEST_LIST = 'home/RECEIVE_REQUEST_LIST';
export const RECEIVE_EMPTY_REQUEST = 'home/RECEIVE_EMPTY_REQUEST';
export const SIGNED_OUT = 'home/SIGNED_OUT';
export const RECEIVE_DETAILED_VIEW = 'home/RECEIVE_DETAILED_VIEW';
export const RECEIVE_EMPTY_DETAILS = 'home/RECEIVE_EMPTY_DETAILS';
